jwt:
  header: Authorization
  secret: Z29vcm10aG9uLWRvY2tlci1wcm9qZWN0LWF1dGgtc2VydmljZS1qd3QtYXV0aG9yaXphdGlvbi1rZXktZ29vcm10aG9kLWRvY2tlci1wcm9qZWN0LWF1dGgtc2VydmljZQo=
  access-token-validity-in-seconds: 1800 # 초 단위
  refresh-token-validity-in-seconds: 604800

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: e67ba6052e23676fbc3d
            client-secret: d2a204d51d9c7d024eaabd16a29542177ed85922
